### ISSUE TITLE
Menu buttons and widgets should be added to Home screen

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#15]
Only search bar is placed in our Home screen for now.

We should add some buttons and / or widgets such as;
- My Groups
- Recommended Groups
- Recommended Meetings

**Update - 19.12.2015**

Based on our discussions below, here are the proposed UI objects in the home screen:
- Upcoming Meetings
- New Messages
- Popular Discussions
- Popular Groups
- Popular Tags

These are suggestions, they will be added based on UX decisions of the mobile team.

**Comment by OrkunKocyigit** [comment]
Hello,
Search bar will be added to group and messaging screens. As for others recommend groups are fully implement but it is hidden from end users as there were no webservice behind it. As far as I know, there is no functionality as get recommended meetings but get earlier meetings. If there is let me know. For other two screen, right now they are literally white space if service returned no data. I will add null screen in case user enters these screens with no data to inform users.

**Comment by OrkunKocyigit** [comment]
Hello,
If we put Recommended Groups in the home screen, home screen will be same as group screen. So I am proposing instead we should put getPopularGroups service or some other UI object.
Thanks.

**Comment by cakyel** [comment]
Hello Orkun,

You are right, let's do that way. Is it reasonable to put some "new message" or "new activity in your groups" notification box?

**Comment by cakyel** [comment]
Other thoughts:
- Upcoming meetings
- Hot discussions
- Popular tags

**Comment by OrkunKocyigit** [comment]
Um, for those you need to ask backhand people to write us a notification services. If they do, I can implement it.

**Comment by cakyel** [comment]
Hmm, let's forget about notifications since this is not our main goal and do not exist in the RSD.

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing group which the user is joined,
> **WHEN** the user logs in to Pink Elephant via mobile application,
> **THEN** the Home screen is loaded.
- [x] Home screen is loaded successfully when the user is logged in
- [x] Active buttons are functional and redirected successfully to the regarding screen

**Comment by cakyel** [comment]
@OrkunKocyigit meetings are not listed while a meeting is existing in Amsterdam Lovers group. Is it because attendants are not yet implemented?

![image](https://cloud.githubusercontent.com/assets/4705964/12072935/e33a89e4-b108-11e5-860e-c3a90a248dfb.png)

**Comment by OrkunKocyigit** [comment]
Are your user invited meeting as a participant?

**Comment by cakyel** [comment]
A user cannot be invited to a meeting so I cannot test it right now.
