### ISSUE TITLE
Placeholder text should be removed from My Profile

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#16]
In My Profile page, empty information were filled as "Placeholder". It should not be shown even if the value is empty.

**Comment by OrkunKocyigit** [comment]
Hello,
Right now,my profile screen hasn't connected to the webservice. I am closing this issue. Can you please open a new issue about connecting my profile screen to webservice?

**Comment by cakyel** [comment]
Alright:

https://github.com/swe574-2015fall-group2/android_repo/issues/22
