### ISSUE TITLE
Data attributes in My Profile screen should be revised.

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#17]
- User name (email) should be added
- Birthdate should be added
- Does Join Date necessary?
- What is Total Contribution?

**Comment by OrkunKocyigit** [comment]
Hello,
Username will be added. Other attributes were model after the Pink Elephant website during it is earlier design. Those will be removed as well if it has decided that they are useless.

**Comment by cakyel** [comment]
Hello Orkun,

Join Date and Total Contribution attributes are not necessary in the current RSD. We can remove them.

**Comment by OrkunKocyigit** [comment]
Hello @cakyel ,
Do we still have privacy setting or are they removed as well?

**Comment by cakyel** [comment]
Hello @OrkunKocyigit ,

A user may change the incoming message setting via My Profile page in the web project.

![image](https://cloud.githubusercontent.com/assets/4705964/11767669/c638037c-a1bc-11e5-8bd2-6de1be229b87.png)
