### ISSUE TITLE
Implement the privacy setting screen

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/android_repo#29]
As the issue #17 states, moble application should provide same options. An alert dialog should be enough.

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there are two existing users and one user is logged in via mobile application,
> **WHEN** the user selects privacy setting and taps Save button
> **THEN** the choice is saved and privacy setting is functional.
- [x] Privacy screen is opened
- [x] Privacy choices are loaded
- [x] Privacy choices can be selected
- [x] Privacy choices can be saved
- [ ] Privacy choices are functional

**Comment by OrkunKocyigit** [comment]
Can you tell me what are the choices in privacy screen?

**Comment by cakyel** [comment]
- Any user can send me a message
- No one can send me a message

![image](https://cloud.githubusercontent.com/assets/4705964/11919230/61d8f532-a755-11e5-9153-8b0a29256745.png)

http://162.243.215.160/Content/#/my_profile

**Comment by cakyel** [comment]
All OK but privacy choices are not functional because service is not yet implemented. It will be reopened when the service is done.
