### ISSUE TITLE
ContactPersonName, ContactPersonEmail and ContactPersonPhone attributes should be added to activity_view_meeting.xml Layout File

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#32]
Based on Week 12 Class Meeting and RSD Rev 1.6, the following data attributes should be added to activity_view_meeting.xml.
- ContactPersonName
- ContactPersonEmail
- ContactPersonPhone

https://piazza.com/class/if3ll4yun9p306?cid=103

https://piazza.com/class/if3ll4yun9p306?cid=103

Related back end issue:
swe574-2015fall-group2/core_repo#245

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing meeting in an existing group and the user is logged in via mobile application,
> **WHEN** the user opens the meeting details screen
> **THEN** Contact Person Name, Contact Person E-mail and Contact Person Phone are listed.
- [ ] Meeting details screen is loaded
- [ ] Contact Person attributes are loaded
- [ ] Contact Person attributes are correct

**Comment by OrkunKocyigit** [comment]
Fixed
