### ISSUE TITLE
My Profile - Upload Profile Picture

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#36]
When profile picture is uploaded via Gallery, the application crashes

![image](https://cloud.githubusercontent.com/assets/4705964/11919603/5fc366c4-a75f-11e5-9c58-b9b99b52b3f8.png)

Profile picture also cannot be choosed from Downloads folder:

![image](https://cloud.githubusercontent.com/assets/4705964/11919610/ab50a0ca-a75f-11e5-8b25-c3539e749af3.png)

![image](https://cloud.githubusercontent.com/assets/4705964/11919612/b746c2d8-a75f-11e5-8b40-1e46c25a9756.png)

Error message:

12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime: Process: swe574.boun.edu.androidproject, PID: 12548
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:300)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: Response code is not valid
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.tasks.UploadProfilePictureTask.doInBackground(UploadProfilePictureTask.java:90)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at swe574.boun.edu.androidproject.tasks.UploadProfilePictureTask.doInBackground(UploadProfilePictureTask.java:27)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
12-20 14:20:15.351 12548-12591/swe574.boun.edu.androidproject E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)

**Comment by OrkunKocyigit** [comment]
Can you send me the problem picture?

**Comment by cakyel** [comment]
I tried to send the downloaded pictures from android demo instance to my e-mail but they come in broken format.

Here are the original files.

![057b4ac](https://cloud.githubusercontent.com/assets/4705964/11919846/faa041c0-a765-11e5-952f-32a82221dafc.jpg)

![hca](https://cloud.githubusercontent.com/assets/4705964/11919847/faca546a-a765-11e5-89e6-0fa16649d9e3.png)

**Comment by OrkunKocyigit** [comment]
Backend problem. The issue about this is opened here: https://github.com/swe574-2015fall-group2/core_repo/issues/248
