### ISSUE TITLE
Group Details Screen - Home panel should be renamed

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#37]
The home screen of our application is already called as Home. 

We should rename this home page as "Group" or "Group Home". Otherwise users may get confused.

![image](https://cloud.githubusercontent.com/assets/4705964/11919629/6a7748e6-a760-11e5-9ba7-98305aa92e07.png)

**Comment by OrkunKocyigit** [comment]
Renamed to what?

**Comment by cakyel** [comment]
Tested OK

![image](https://cloud.githubusercontent.com/assets/4705964/11919904/a6d8bf0c-a767-11e5-8611-93fb6e54af62.png)
