### ISSUE TITLE
Join Group - Redirection to the joined group

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#38]
A user should be redirected to the joined group screen, when he/she applied for it.

![image](https://cloud.githubusercontent.com/assets/4705964/11919642/c05c3d66-a760-11e5-9ce2-6dbb11c03e89.png)

**Comment by OrkunKocyigit** [comment]
Problem is while it will work on demo as you can automaticly join any group as you want. In real version your application need to be granted by an admin. Henceforth it is not a realistic case.

**Comment by cakyel** [comment]
So this case is obsolete and I can close this issue?

**Comment by OrkunKocyigit** [comment]
Pretty much
