### ISSUE TITLE
Home Screen - Group Screen revisions

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#39]
What is the use of Home Screen in the current version? Maybe the application should load Group Screen as the home screen?

![image](https://cloud.githubusercontent.com/assets/4705964/11919657/7ef1cea8-a761-11e5-9bf2-cd5652853c5f.png)

![image](https://cloud.githubusercontent.com/assets/4705964/11919661/8c2063aa-a761-11e5-98fd-c72024f9c145.png)

**Comment by OrkunKocyigit** [comment]
Fixed with #15
