### ISSUE TITLE
Group Screen - Meetings - Existing meeting is not listed

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#41]
Existing meeting is not listed in the screen.

Example group name: csdcs

Example meeting: test

![image](https://cloud.githubusercontent.com/assets/4705964/11919715/f2f0e298-a762-11e5-9446-2a1bdc24648c.png)

**Comment by OrkunKocyigit** [comment]
Ok, this is actually a bug. I'll check this.

**Comment by cakyel** [comment]
Is it OK?

I cannot see the existing meeting of the group "csdcs"

![image](https://cloud.githubusercontent.com/assets/4705964/11919912/f7a402f2-a767-11e5-9044-8a20c52b94d5.png)

**Comment by OrkunKocyigit** [comment]
Okay, I will recheck

**Comment by OrkunKocyigit** [comment]
Can you test the results?

**Comment by cakyel** [comment]
It works perfectly, thanks @OrkunKocyigit 

Just one thing, I will change meeting description with meeting name.

You can find some examples in the Aston Martin DBS Lovers group:

![image](https://cloud.githubusercontent.com/assets/4705964/12008231/e5b8f2dc-ac35-11e5-92d2-74f3f0240f13.png)

**Comment by cakyel** [comment]
Meeting list with meeting name:

![image](https://cloud.githubusercontent.com/assets/4705964/12008276/c44e944a-ac39-11e5-9478-fccbacafb118.png)
