### ISSUE TITLE
Group Screen - Discussions - Existing discussion is not listed

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#42]
Existing discussion is not listed in the screen.

Example group name: csdcs

Example discussion: Test Discussion

![image](https://cloud.githubusercontent.com/assets/4705964/11919718/103bdd12-a763-11e5-91ee-a1d60b0ea1f6.png)

**Comment by OrkunKocyigit** [comment]
It is not a bug. This functionality is work in progress
