### ISSUE TITLE
Group Screen - Notes - Existing note is not listed

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#43]
Existing note is not listed in the screen.

Example group name: csdcs

Example note: test

![image](https://cloud.githubusercontent.com/assets/4705964/11919720/29b929a2-a763-11e5-8f65-5e1e33d2a87a.png)

**Comment by OrkunKocyigit** [comment]
It is not a bug. This functionality is work in progress

**Comment by OrkunKocyigit** [comment]
#50, is the related issue for the implementition.
