### ISSUE TITLE
Group Details Screen - Long description messed up the layout

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#47]
Long description messed up the layout

Example group: Curling at the Winter Olympics

![image](https://cloud.githubusercontent.com/assets/4705964/11921297/6dcd66dc-a78e-11e5-8f75-f3ce1fe2385d.png)

**Comment by OrkunKocyigit** [comment]
I am pretty sure I fixed this, can you retry after a resync?

**Comment by cakyel** [comment]
Hello Orkun, today we saw that this problem exists. Can you please check it again?

**Comment by cakyel** [comment]
Tested OK but isn't it too short? Is there a way to give more length to description without messing up the design? @OrkunKocyigit 

![image](https://cloud.githubusercontent.com/assets/4705964/11967431/69efc1c6-a90b-11e5-8814-1f0a1ac09555.png)
