### ISSUE TITLE
Write complex validations

### ISSUE THREAD

**Issue by OrkunKocyigit** [swe574-2015fall-group2/android_repo#7]

**Comment by cakyel** [comment]
@OrkunKocyigit can you give more detail about this issue? Thanks.

**Comment by OrkunKocyigit** [comment]
Hello,
As it is, mobile application doesn't verify the data which user enters. Verification will ensure that the entered data will fit to our standarts.

**Comment by OrkunKocyigit** [comment]
These functionality are implemented for the current screens.
