### ISSUE TITLE
Note Details - Static Resource text should be replaced

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#73]
There is a static text in resource box in note details screen. It should be replaced with a text such as "No resources attached"

User: amy@winehouse.com
Pass: amy123
Group: Amsterdam Lovers
Note: My Amsterdam Notes

![image](https://cloud.githubusercontent.com/assets/4705964/12076652/bd74b1bc-b1bc-11e5-9f55-df56da90b338.png)

**Comment by OrkunKocyigit** [comment]
Um, I don't have any static content on Mobile App.Here is my request for Note 1:
{
    "authToken": "8804d3b0-b200-11e5-9c45-04019494e201",
    "groupId": "56844ea1e4b0d46054a91c48",
    "noteId": "5684fa43e4b08f9c999e373e"
}
Here is response for Note 1:
{
    "status": "success",
    "result": [{
        "id": "5684f979e4b08f9c999e373d",
        "description": "Enhancing the Effective Communication in Distributed Agile Environment.pdf",
        "entityType": "RESOURCE",
        "type": "INTERNAL",
        "group": {
            "id": "56844ea1e4b0d46054a91c48",
            "description": "Join our group to talk about Amsterdam",
            "entityType": "GROUP",
            "name": "Amsterdam Lovers",
            "status": "ACTIVE",
            "createdAt": 1451511457842,
            "creator": {
                "id": "56842f03e4b04720e337512d",
                "username": "mehmetcelikel@gmail.com",
                "firstname": "Mehmet",
                "lastname": "Celikel",
                "password": "test",
                "roles": [{
                    "groupId": "56845184e4b08f9c999e3733",
                    "groupRoles": [{
                        "id": "56844e2fe4b0d46054a91c47",
                        "name": "all_permissions",
                        "permissions": ["create_discussion",
                        "update_discussion",
                        "comment_to_discussion",
                        "add_remove_tag_to_discussion",
                        "create_meeting",
                        "update_meeting",
                        "invite_user_to_meeting",
                        "create_meeting_proposal",
                        "update_meeting_proposal",
                        "delete_meeting_proposal",
                        "delete_meeting"]
                    }]
                },
                {
                    "groupId": "56886d95e4b0e69ba401f26c",
                    "groupRoles": [{
                        "id": "56844e2fe4b0d46054a91c47",
                        "name": "all_permissions",
                        "permissions": ["create_discussion",
                        "update_discussion",
                        "comment_to_discussion",
                        "add_remove_tag_to_discussion",
                        "create_meeting",
                        "update_meeting",
                        "invite_user_to_meeting",
                        "create_meeting_proposal",
                        "update_meeting_proposal",
                        "delete_meeting_proposal",
                        "delete_meeting"]
                    }]
                }],
                "userDetail": {
                    "birthDate": "2015-12-29",
                    "profession": "string",
                    "university": "string",
                    "programme": "string",
                    "interestedAreas": "string",
                    "linkedinProfile": "string",
                    "academiaProfile": "string"
                },
                "status": "ACTIVE"
            }
        },
        "createdAt": 1451555193569,
        "creator": {
            "id": "56842f03e4b04720e337512d",
            "username": "mehmetcelikel@gmail.com",
            "firstname": "Mehmet",
            "lastname": "Celikel",
            "password": "test",
            "roles": [{
                "groupId": "56845184e4b08f9c999e3733",
                "groupRoles": [{
                    "id": "56844e2fe4b0d46054a91c47",
                    "name": "all_permissions",
                    "permissions": ["create_discussion",
                    "update_discussion",
                    "comment_to_discussion",
                    "add_remove_tag_to_discussion",
                    "create_meeting",
                    "update_meeting",
                    "invite_user_to_meeting",
                    "create_meeting_proposal",
                    "update_meeting_proposal",
                    "delete_meeting_proposal",
                    "delete_meeting"]
                }]
            },
            {
                "groupId": "56886d95e4b0e69ba401f26c",
                "groupRoles": [{
                    "id": "56844e2fe4b0d46054a91c47",
                    "name": "all_permissions",
                    "permissions": ["create_discussion",
                    "update_discussion",
                    "comment_to_discussion",
                    "add_remove_tag_to_discussion",
                    "create_meeting",
                    "update_meeting",
                    "invite_user_to_meeting",
                    "create_meeting_proposal",
                    "update_meeting_proposal",
                    "delete_meeting_proposal",
                    "delete_meeting"]
                }]
            }],
            "userDetail": {
                "birthDate": "2015-12-29",
                "profession": "string",
                "university": "string",
                "programme": "string",
                "interestedAreas": "string",
                "linkedinProfile": "string",
                "academiaProfile": "string"
            },
            "status": "ACTIVE"
        }
    },
    {
        "id": "5687c425e4b0fdc7d76a2036",
        "description": "Enhancing the Effective Communication in Distributed Agile Environment.pdf",
        "entityType": "RESOURCE",
        "type": "INTERNAL",
        "group": {
            "id": "56844ea1e4b0d46054a91c48",
            "description": "Join our group to talk about Amsterdam",
            "entityType": "GROUP",
            "name": "Amsterdam Lovers",
            "status": "ACTIVE",
            "createdAt": 1451511457842,
            "creator": {
                "id": "56842f03e4b04720e337512d",
                "username": "mehmetcelikel@gmail.com",
                "firstname": "Mehmet",
                "lastname": "Celikel",
                "password": "test",
                "roles": [{
                    "groupId": "56845184e4b08f9c999e3733",
                    "groupRoles": [{
                        "id": "56844e2fe4b0d46054a91c47",
                        "name": "all_permissions",
                        "permissions": ["create_discussion",
                        "update_discussion",
                        "comment_to_discussion",
                        "add_remove_tag_to_discussion",
                        "create_meeting",
                        "update_meeting",
                        "invite_user_to_meeting",
                        "create_meeting_proposal",
                        "update_meeting_proposal",
                        "delete_meeting_proposal",
                        "delete_meeting"]
                    }]
                },
                {
                    "groupId": "56886d95e4b0e69ba401f26c",
                    "groupRoles": [{
                        "id": "56844e2fe4b0d46054a91c47",
                        "name": "all_permissions",
                        "permissions": ["create_discussion",
                        "update_discussion",
                        "comment_to_discussion",
                        "add_remove_tag_to_discussion",
                        "create_meeting",
                        "update_meeting",
                        "invite_user_to_meeting",
                        "create_meeting_proposal",
                        "update_meeting_proposal",
                        "delete_meeting_proposal",
                        "delete_meeting"]
                    }]
                }],
                "userDetail": {
                    "birthDate": "2015-12-29",
                    "profession": "string",
                    "university": "string",
                    "programme": "string",
                    "interestedAreas": "string",
                    "linkedinProfile": "string",
                    "academiaProfile": "string"
                },
                "status": "ACTIVE"
            }
        },
        "createdAt": 1451738149064,
        "creator": {
            "id": "5687c3c5e4b0fdc7d76a2034",
            "username": "bariso@gmail.com",
            "firstname": "Baris",
            "lastname": "Ozcanli",
            "password": "test",
            "roles": [{
                "groupId": "56844ea1e4b0d46054a91c48",
                "groupRoles": [{
                    "id": "56844e2fe4b0d46054a91c47",
                    "name": "all_permissions",
                    "permissions": ["create_discussion",
                    "update_discussion",
                    "comment_to_discussion",
                    "add_remove_tag_to_discussion",
                    "create_meeting",
                    "update_meeting",
                    "invite_user_to_meeting",
                    "create_meeting_proposal",
                    "update_meeting_proposal",
                    "delete_meeting_proposal",
                    "delete_meeting"]
                }]
            }],
            "userDetail": {

```
        },
        "status": "ACTIVE"
    }
},
{
    "id": "5687c488e4b0fdc7d76a2037",
    "description": "Enhancing the Effective Communication in Distributed Agile Environment.pdf",
    "entityType": "RESOURCE",
    "type": "INTERNAL",
    "group": {
        "id": "56844ea1e4b0d46054a91c48",
        "description": "Join our group to talk about Amsterdam",
        "entityType": "GROUP",
        "name": "Amsterdam Lovers",
        "status": "ACTIVE",
        "createdAt": 1451511457842,
        "creator": {
            "id": "56842f03e4b04720e337512d",
            "username": "mehmetcelikel@gmail.com",
            "firstname": "Mehmet",
            "lastname": "Celikel",
            "password": "test",
            "roles": [{
                "groupId": "56845184e4b08f9c999e3733",
                "groupRoles": [{
                    "id": "56844e2fe4b0d46054a91c47",
                    "name": "all_permissions",
                    "permissions": ["create_discussion",
                    "update_discussion",
                    "comment_to_discussion",
                    "add_remove_tag_to_discussion",
                    "create_meeting",
                    "update_meeting",
                    "invite_user_to_meeting",
                    "create_meeting_proposal",
                    "update_meeting_proposal",
                    "delete_meeting_proposal",
                    "delete_meeting"]
                }]
            },
            {
                "groupId": "56886d95e4b0e69ba401f26c",
                "groupRoles": [{
                    "id": "56844e2fe4b0d46054a91c47",
                    "name": "all_permissions",
                    "permissions": ["create_discussion",
                    "update_discussion",
                    "comment_to_discussion",
                    "add_remove_tag_to_discussion",
                    "create_meeting",
                    "update_meeting",
                    "invite_user_to_meeting",
                    "create_meeting_proposal",
                    "update_meeting_proposal",
                    "delete_meeting_proposal",
                    "delete_meeting"]
                }]
            }],
            "userDetail": {
                "birthDate": "2015-12-29",
                "profession": "string",
                "university": "string",
                "programme": "string",
                "interestedAreas": "string",
                "linkedinProfile": "string",
                "academiaProfile": "string"
            },
            "status": "ACTIVE"
        }
    },
    "createdAt": 1451738248245,
    "creator": {
        "id": "5687c3c5e4b0fdc7d76a2034",
        "username": "bariso@gmail.com",
        "firstname": "Baris",
        "lastname": "Ozcanli",
        "password": "test",
        "roles": [{
            "groupId": "56844ea1e4b0d46054a91c48",
            "groupRoles": [{
                "id": "56844e2fe4b0d46054a91c47",
                "name": "all_permissions",
                "permissions": ["create_discussion",
                "update_discussion",
                "comment_to_discussion",
                "add_remove_tag_to_discussion",
                "create_meeting",
                "update_meeting",
                "invite_user_to_meeting",
                "create_meeting_proposal",
                "update_meeting_proposal",
                "delete_meeting_proposal",
                "delete_meeting"]
            }]
        }],
        "userDetail": {

        },
        "status": "ACTIVE"
    }
}]
```

}
