### ISSUE TITLE
New Discussion Screen - Create Group button should be renamed as Create Discussion

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/android_repo#74]
User: amy@winehouse.com
Pass: amy123
Group: Amsterdam Lovers

![image](https://cloud.githubusercontent.com/assets/4705964/12076662/58138b58-b1bd-11e5-99c0-a3f468df0b1e.png)

**Comment by cakyel** [comment]
Tested OK

![image](https://cloud.githubusercontent.com/assets/4705964/12076784/bfc69636-b1c3-11e5-9869-ac0e24bab737.png)

**Comment by OrkunKocyigit** [comment]
This will create an issue with Note's, as they use the same activity.
